name: Case study inspired by Mistral LCA. 
description: SCI4AI case study inspired by Mistral LCA at https://mistral.ai/news/our-contribution-to-a-global-environmental-standard-for-ai
tags:
aggregation:
  metrics:
    - carbon
  type: component
initialize:
  plugins:
    arbitrary-op:
      path: builtin
      method: Coefficient
      config:
        input-parameter: carbon
        coefficient: 1
        output-parameter: carbon    
      parameter-metadata:
        inputs:
          carbon:
            unit: gCO2e
            description: carbon emission
            aggregation-method:
              time: sum
              component: sum
    amortize-embodied:
      path: builtin
      method: Multiply
      config:
        input-parameters: ['embodied-carbon', 'amortization-factor'] # amortization factor is time used / total lifespan
        output-parameter: 'carbon'    
      parameter-metadata:
        inputs:
          carbon:
            unit: gCO2e
            description: carbon emission
            aggregation-method:
              time: sum
              component: sum
tree:
  children:
    model-conception:
      children:
        download-and-storage-of-training-data:
        # we'll assume 11 Trillion words used to train model (same as Llama3) at 5bytes/word = 55 Trillion bytes (i.e. 55 TB))
        # note we're omitting data-center supporting infra for now - e.g. racks, PDU, UPS, cooling allocation, etc
          children:
            embodied:
              children:
                storage-servers: # assume we use 2U server with 12x 16TB HDDs, e.g. https://www.broadberry.co.uk/xeon-e-rackmount-servers/cyberserve-xeon-e-212s-g14 - estimated 800kg of embodied emissions
                  pipeline:
                    compute:
                      - amortize-embodied
                  inputs:
                    - timestamp: '2025-01-01T00:00:00.000Z'
                      duration: 7889400
                      embodied-carbon: 800000
                      amortization-factor: 0.0625 # assume this is in use for a 3 month training period
                switch: # 10GbE 48 port enterprise switch for storage network
                  pipeline:
                    compute:
                      - amortize-embodied
                  inputs:
                    - timestamp: '2025-01-01T00:00:00.000Z'
                      duration: 7889400
                      embodied-carbon: 300000 # assuming 300 kg embodied
                      amortization-factor: 0.0625 # assume this is in use foir a 3 month training period
                network-cards: # assume 8 cards
                  pipeline:
                    compute:
                      - amortize-embodied
                  inputs:
                    - timestamp: '2025-01-01T00:00:00.000Z'
                      duration: 7889400
                      embodied-carbon: 160000 # assuming 160 kg embodied for all 8 servers
                      amortization-factor: 0.0625 # assume this is in use foir a 3 month training period
                preprocessing-server: # single 2U server for data deduplication and preparation, 2 CPUs, 256 GB RAM
                  pipeline:
                    compute:
                      - amortize-embodied
                  inputs:
                    - timestamp: '2025-01-01T00:00:00.000Z'
                      duration: 7889400
                      embodied-carbon: 600000 # assuming 160 kg embodied for all 8 servers
                      amortization-factor: 0.0625 # assume this is in use foir a 3 month training period
                    
            operational:
              pipeline:
                compute:
                  - arbitrary-op
              inputs:
                - timestamp: '2025-01-01T00:00:00.000Z'
                  duration: 3600
                  carbon: 600000
        developers-laptops:
          children:
            embodied:
              pipeline:
                compute:
                  - arbitrary-op
              inputs:
                - timestamp: '2025-01-01T00:00:00.000Z'
                  duration: 3600
                  carbon: 4000000
            operational:
              pipeline:
                compute:
                  - arbitrary-op
              inputs:
                - timestamp: '2025-01-01T00:00:00.000Z'
                  duration: 3600
                  carbon: 600000
    datacenter-construction:
      children:
        embodied:
          pipeline:
            compute:
              - arbitrary-op
          inputs:
            - timestamp: '2025-01-01T00:00:00.000Z'
              duration: 3600
              carbon: 4000000
        operational:
          pipeline:
            compute:
              - arbitrary-op
          inputs:
            - timestamp: '2025-01-01T00:00:00.000Z'
              duration: 3600
              carbon: 600000
    model-training:
      children:
        embodied:
          pipeline:
            compute:
              - arbitrary-op
          inputs:
            - timestamp: '2025-01-01T00:00:00.000Z'
              duration: 3600
              carbon: 4000000
        operational:
          pipeline:
            compute:
              - arbitrary-op
          inputs:
            - timestamp: '2025-01-01T00:00:00.000Z'
              duration: 3600
              carbon: 600000
    model-inference:
      children:
        embodied:
          pipeline:
            compute:
              - arbitrary-op
          inputs:
            - timestamp: '2025-01-01T00:00:00.000Z'
              duration: 3600
              carbon: 4000000
        operational:
          pipeline:
            compute:
              - arbitrary-op
          inputs:
            - timestamp: '2025-01-01T00:00:00.000Z'
              duration: 3600
              carbon: 600000
    network-traffic-of-tokens:
      children:
        embodied:
          pipeline:
            compute:
              - arbitrary-op
          inputs:
            - timestamp: '2025-01-01T00:00:00.000Z'
              duration: 3600
              carbon: 4000000
        operational:
          pipeline:
            compute:
              - arbitrary-op
          inputs:
            - timestamp: '2025-01-01T00:00:00.000Z'
              duration: 3600
              carbon: 600000
    end-user-equipment:
      children:
        embodied:
          pipeline:
            compute:
              - arbitrary-op
          inputs:
            - timestamp: '2025-01-01T00:00:00.000Z'
              duration: 3600
              carbon: 4000000
        operational:
          pipeline:
            compute:
              - arbitrary-op
          inputs:
            - timestamp: '2025-01-01T00:00:00.000Z'
              duration: 3600
              carbon: 600000
