name: GSF Website SCI
description: generates SCI score (gCO2eq/visit) for greensoftware.foundation website
tags: null
aggregation:
  metrics:
    - carbon
    - sci
  type: both
initialize:
  plugins:
    duration-in-hours:
      path: builtin
      method: Divide
      config:
        numerator: duration
        denominator: 3600
        output: duration-in-hours
    storage-and-traffic-from-github-if-docs:
      path: if-github-plugin
      method: Github
      mapping:
        size: repo-size-if-docs
        clones: repo-clones-if-docs
      config:
        repo: Green-Software-Foundation/if-docs
    storage-in-gb-to-tb-if-docs:
      path: builtin
      method: Coefficient
      config:
        input-parameter: repo-size-if-docs
        coefficient: 0.001
        output-parameter: storage-tb-if-docs
    storage-energy-in-watts-if-docs:
      path: builtin
      method: Multiply
      config:
        input-parameters:
          - storage-tb-if-docs
          - watts-per-tb
        output-parameter: storage-watts-if-docs
    storage-energy-in-wh-if-docs:
      path: builtin
      method: Multiply
      config:
        input-parameters:
          - storage-watts-if-docs
          - duration-in-hours
        output-parameter: storage-wh-if-docs
    storage-energy-to-kwh-if-docs:
      path: builtin
      method: Coefficient
      config:
        input-parameter: storage-wh-if-docs
        coefficient: 0.001
        output-parameter: energy
    energy-to-carbon:
      path: builtin
      method: Multiply
      config:
        input-parameters:
          - energy
          - grid-intensity
        output-parameter: carbon
    static-site-size-in-tb:
      path: builtin
      method: Divide
      config:
        numerator: static-site-size-in-mb
        denominator: 1000000
        output: static-site-size-in-tb
    storage-energy-static-site-in-watts:
      path: builtin
      method: Multiply
      config:
        input-parameters:
          - static-site-size-in-tb
          - watts-per-tb
        output-parameter: storage-watts-static-site-at-origin
    storage-energy-in-wh-static-site:
      path: builtin
      method: Multiply
      config:
        input-parameters:
          - storage-watts-static-site-at-origin
          - duration-in-hours
        output-parameter: storage-wh-static-site-at-origin
    storage-energy-to-kwh-static-site:
      path: builtin
      method: Coefficient
      config:
        input-parameter: storage-wh-static-site-at-origin
        coefficient: 0.001
        output-parameter: storage-energy-kwh-static-site-at-origin
    storage-energy-per-cdn-node:
      path: builtin
      method: Divide
      config:
        numerator: storage-energy-kwh-static-site-at-origin
        denominator: 10
        output: storage-energy-per-cdn-node
    storage-energy-for-entire-cdn:
      path: builtin
      method: Coefficient
      config:
        input-parameter: storage-energy-per-cdn-node
        coefficient: 46
        output-parameter: storage-energy-whole-cdn
    sum-serving-static-site-energy-components:
      path: builtin
      method: Sum
      config:
        input-parameters:
          - storage-energy-whole-cdn
          - storage-energy-kwh-static-site-at-origin
        output-parameter: energy
    static-site-size-in-gb:
      path: builtin
      method: Coefficient
      config:
        input-parameter: static-site-size-in-mb
        coefficient: 0.000001
        output-parameter: static-site-size-in-gb
    network-energy-serving-static-site-per-view:
      path: builtin
      method: Multiply
      config:
        input-parameters:
          - static-site-size-in-gb
          - kwh-per-gb-network
        output-parameter: network-energy-kwh-serving-static-site-per-view
    network-energy-serving-static-site-total:
      path: builtin
      method: Multiply
      config:
        input-parameters:
          - network-energy-kwh-serving-static-site-per-view
          - visits-per-month
        output-parameter: energy
    end-user-energy:
      path: builtin
      method: Multiply
      config:
        input-parameters:
          - visits-per-month
          - static-site-size-in-gb
          - end-user-energy-coefficient
        output-parameter: energy
    interpolate-power-curve:
      path: builtin
      method: Interpolation
      config:
        method: linear
        x:
          - 0
          - 10
          - 50
          - 100
        'y':
          - 0.12
          - 0.32
          - 0.75
          - 1.02
        input-parameter: cpu-utilization-during-build
        output-parameter: cpu-factor
    build-stage-cpu-factor-to-wattage:
      path: builtin
      method: Multiply
      config:
        input-parameters:
          - cpu-factor
          - thermal-design-power
        output-parameter: cpu-wattage
    build-stage-cpu-wattage-times-build-duration:
      path: builtin
      method: Multiply
      config:
        input-parameters:
          - cpu-wattage
          - build-duration
        output-parameter: cpu-wattage-times-duration
    build-stage-cpu-wattage-to-energy-kwh:
      path: builtin
      method: Divide
      config:
        numerator: cpu-wattage-times-duration
        denominator: 3600000
        output: build-energy-cpu-kwh
    memory-coefficient-correction:
      path: builtin
      method: Coefficient
      config:
        input-parameter: build-duration
        coefficient: 0.000006533333
        output-parameter: memory-coefficient
    memory-energy-per-build:
      path: builtin
      method: Multiply
      config:
        input-parameters:
          - build-memory-gb
          - memory-coefficient
        output-parameter: build-energy-memory-kwh
    sum-build-energy-components:
      path: builtin
      method: Sum
      config:
        input-parameters:
          - build-energy-cpu-kwh
          - build-energy-memory-kwh
        output-parameter: build-energy-kwh-per-build
    build-energy-total:
      path: builtin
      method: Multiply
      config:
        input-parameters:
          - build-energy-kwh-per-build
          - builds-per-month
        output-parameter: energy
    sci:
      path: builtin
      method: Sci
      config:
        functional-unit: visits-per-month
execution:
  command: >-
    /home/joe/.npm/_npx/1bf7c3c15bf47d04/node_modules/.bin/ts-node
    /home/joe/Code/if/src/if-run/index.ts -m
    manifests/examples/if-website-sci.yml -o
    manifests/outputs/if-website-sci-output
  environment:
    if-version: 0.6.0
    os: linux
    os-version: 5.15.0-117-generic
    node-version: 21.4.0
    date-time: 2024-08-21T14:06:00.960Z (UTC)
    dependencies:
      - '@babel/core@7.22.10'
      - '@babel/preset-typescript@7.23.3'
      - '@commitlint/cli@18.6.0'
      - '@commitlint/config-conventional@18.6.0'
      - '@grnsft/if-core@0.0.17'
      - '@jest/globals@29.7.0'
      - '@types/jest@29.5.8'
      - '@types/js-yaml@4.0.9'
      - '@types/luxon@3.4.2'
      - '@types/node@20.9.0'
      - axios-mock-adapter@1.22.0
      - axios@1.7.2
      - cross-env@7.0.3
      - csv-parse@5.5.6
      - csv-stringify@6.4.6
      - fixpack@4.0.0
      - gts@5.2.0
      - husky@8.0.3
      - if-eco-ci-plugin@v0.0.1 extraneous -> file:../../if-eco-ci-plugin
      - if-github-plugin@v0.0.1 extraneous -> file:../../if-github-plugin
      - jest@29.7.0
      - js-yaml@4.1.0
      - lint-staged@15.2.2
      - luxon@3.4.4
      - release-it@16.3.0
      - rimraf@5.0.5
      - ts-command-line-args@2.5.1
      - ts-jest@29.1.1
      - typescript-cubic-spline@1.0.1
      - typescript@5.2.2
      - winston@3.11.0
      - zod@3.23.8
  status: success
tree:
  children:
    github-storage-for-if-docs:
      pipeline:
        compute:
          - duration-in-hours
          - storage-and-traffic-from-github-if-docs
          - storage-in-gb-to-tb-if-docs
          - storage-energy-in-watts-if-docs
          - storage-energy-in-wh-if-docs
          - storage-energy-to-kwh-if-docs
          - energy-to-carbon
          - sci
      defaults:
        watts-per-tb: 1.2
        grid-intensity: 765.49
        visits-per-month: 325
      inputs:
        - timestamp: 2024-08-13T00:00
          duration: 2419200
      outputs:
        - timestamp: 2024-08-13T00:00
          duration: 2419200
          watts-per-tb: 1.2
          grid-intensity: 765.49
          visits-per-month: 325
          duration-in-hours: 672
          repo-clones-if-docs: 1
          repo-size-if-docs: 0.011354
          storage-tb-if-docs: 0.000011354
          storage-watts-if-docs: 0.0000136248
          storage-wh-if-docs: 0.0091558656
          energy: 0.0000091558656
          carbon: 0.007008723558144
          sci: 0.000021565303255827694
      aggregated:
        carbon: 0.007008723558144
        sci: 0.000021565303255827694
    storing-static-site-data-on-netlify:
      pipeline:
        compute:
          - duration-in-hours
          - static-site-size-in-tb
          - storage-energy-static-site-in-watts
          - storage-energy-in-wh-static-site
          - storage-energy-to-kwh-static-site
          - storage-energy-per-cdn-node
          - storage-energy-for-entire-cdn
          - sum-serving-static-site-energy-components
          - energy-to-carbon
          - sci
      defaults:
        static-site-size-in-mb: 1.4
        watts-per-tb: 1.2
        grid-intensity: 765.49
        visits-per-month: 325
      inputs:
        - timestamp: 2024-08-13T00:00
          duration: 2419200
      outputs:
        - timestamp: 2024-08-13T00:00
          duration: 2419200
          static-site-size-in-mb: 1.4
          watts-per-tb: 1.2
          grid-intensity: 765.49
          visits-per-month: 325
          duration-in-hours: 672
          static-site-size-in-tb: 0.0000014
          storage-watts-static-site-at-origin: 0.0000016799999999999998
          storage-wh-static-site-at-origin: 0.0011289599999999998
          storage-energy-kwh-static-site-at-origin: 0.0000011289599999999999
          storage-energy-per-cdn-node: 1.1289599999999998e-7
          storage-energy-whole-cdn: 0.000005193215999999999
          energy: 0.0000063221759999999996
          carbon: 0.00483956250624
          sci: 0.000014890961557661539
      aggregated:
        carbon: 0.00483956250624
        sci: 0.000014890961557661539
    networking-energy-to-serve-static-site-over-the-wire:
      pipeline:
        compute:
          - static-site-size-in-gb
          - network-energy-serving-static-site-per-view
          - network-energy-serving-static-site-total
          - energy-to-carbon
          - sci
      defaults:
        static-site-size-in-mb: 1.4
        kwh-per-gb-network: 0.001
        watts-per-tb: 1.2
        grid-intensity: 765.49
        visits-per-month: 325
      inputs:
        - timestamp: 2024-08-13T00:00
          duration: 2419200
      outputs:
        - timestamp: 2024-08-13T00:00
          duration: 2419200
          static-site-size-in-mb: 1.4
          kwh-per-gb-network: 0.001
          watts-per-tb: 1.2
          grid-intensity: 765.49
          visits-per-month: 325
          static-site-size-in-gb: 0.0000014
          network-energy-kwh-serving-static-site-per-view: 1.4e-9
          energy: 4.55e-7
          carbon: 0.00034829795
          sci: 0.000001071686
      aggregated:
        carbon: 0.00034829795
        sci: 0.000001071686
    end-user-operational-carbon:
      pipeline:
        compute:
          - static-site-size-in-gb
          - end-user-energy
          - energy-to-carbon
          - sci
      defaults:
        end-user-energy-coefficient: 0.08
        static-site-size-in-mb: 1.4
        kwh-per-gb-network: 0.001
        grid-intensity: 765.49
        visits-per-month: 325
      inputs:
        - timestamp: 2024-08-13T00:00
          duration: 2419200
      outputs:
        - timestamp: 2024-08-13T00:00
          duration: 2419200
          end-user-energy-coefficient: 0.08
          static-site-size-in-mb: 1.4
          kwh-per-gb-network: 0.001
          grid-intensity: 765.49
          visits-per-month: 325
          static-site-size-in-gb: 0.0000014
          energy: 0.000036400000000000004
          carbon: 0.027863836000000003
          sci: 0.00008573488000000001
      aggregated:
        carbon: 0.027863836000000003
        sci: 0.00008573488000000001
    gh-pages-builds:
      pipeline:
        compute:
          - interpolate-power-curve
          - build-stage-cpu-factor-to-wattage
          - build-stage-cpu-wattage-times-build-duration
          - build-stage-cpu-wattage-to-energy-kwh
          - memory-coefficient-correction
          - memory-energy-per-build
          - sum-build-energy-components
          - build-energy-total
          - energy-to-carbon
          - sci
      defaults:
        end-user-energy-coefficient: 0.08
        static-site-size-in-mb: 0.809473
        kwh-per-gb-network: 0.001
        grid-intensity: 765.49
        visits-per-month: 325
        build-duration: 5
        build-memory-gb: 0.34
        builds-per-month: 3
        thermal-design-power: 205
        cpu-utilization-during-build: 100
      inputs:
        - timestamp: 2024-08-13T00:00
          duration: 2419200
      outputs:
        - timestamp: 2024-08-13T00:00
          duration: 2419200
          end-user-energy-coefficient: 0.08
          static-site-size-in-mb: 0.809473
          kwh-per-gb-network: 0.001
          grid-intensity: 765.49
          visits-per-month: 325
          build-duration: 5
          build-memory-gb: 0.34
          builds-per-month: 3
          thermal-design-power: 205
          cpu-utilization-during-build: 100
          cpu-factor: 1.02
          cpu-wattage: 209.1
          cpu-wattage-times-duration: 1045.5
          build-energy-cpu-kwh: 0.0002904166666666667
          memory-coefficient: 0.000032666665
          build-energy-memory-kwh: 0.000011106666100000002
          build-energy-kwh-per-build: 0.0003015233327666667
          energy: 0.0009045699983000001
          carbon: 0.692439287998667
          sci: 0.0021305824246112834
      aggregated:
        carbon: 0.692439287998667
        sci: 0.0021305824246112834
    embodied-carbon-for-web-server:
      pipeline:
        compute:
          - sci
      defaults:
        visits-per-month: 325
      inputs:
        - timestamp: 2024-08-13T00:00
          duration: 2419200
          carbon: 0.125
      outputs:
        - timestamp: 2024-08-13T00:00
          duration: 2419200
          carbon: 0.125
          visits-per-month: 325
          sci: 0.0003846153846153846
      aggregated:
        carbon: 0.125
        sci: 0.0003846153846153846
    embodied-carbon-for-github-server:
      pipeline:
        compute:
          - sci
      defaults:
        visits-per-month: 325
      inputs:
        - timestamp: 2024-08-13T00:00
          duration: 2419200
          carbon: 0.0071
      outputs:
        - timestamp: 2024-08-13T00:00
          duration: 2419200
          carbon: 0.0071
          visits-per-month: 325
          sci: 0.000021846153846153848
      aggregated:
        carbon: 0.0071
        sci: 0.000021846153846153848
    embodied-carbon-for-end-user-devices:
      pipeline:
        compute:
          - sci
      defaults:
        visits-per-month: 325
      inputs:
        - timestamp: 2024-08-13T00:00
          duration: 2419200
          carbon: 11.34
      outputs:
        - timestamp: 2024-08-13T00:00
          duration: 2419200
          carbon: 11.34
          visits-per-month: 325
          sci: 0.034892307692307695
      aggregated:
        carbon: 11.34
        sci: 0.034892307692307695
  outputs:
    - carbon: 12.20459970801305
      sci: 0.03755261448619401
      timestamp: 2024-08-13T00:00
      duration: 2419200
  aggregated:
    carbon: 12.20459970801305
    sci: 0.03755261448619401
