name: if-sci
description:
tags:
initialize:
  plugins:

    # Unit conversions
    ##################

    duration-in-hours:
      method: Divide
      path: "builtin"
      global-config:
        numerator: duration
        denominator: 3600 # s to hr
        output: duration-in-hours


    ## Github storage for IF
    ########################

    storage-and-traffic-from-github-if:
      method: Github
      path: if-github-plugin
      global-config:
        repo: Green-Software-Foundation/if
    copy-param-if-repo-size:
      path: builtin
      method: Copy
      global-config:
        keep-existing: false
        from: size
        to: "repo-size-if"
    copy-param-if-clones:
      path: builtin
      method: Copy
      global-config:
        keep-existing: false
        from: clones
        to: repo-clones-if
    storage-in-mb-to-tb-if:
      method: Coefficient
      path: builtin
      global-config:
        input-parameter: repo-size-if # size comes from github api and represents repo size in gb
        coefficient: 0.000001 # convert size to tb
        output-parameter: "storage-tb-if"
    storage-energy-in-watts-if:
      method: Multiply
      path: builtin
      global-config:
        input-parameters: ["storage-tb-if", "watts-per-tb"]
        output-parameter: "storage-watts-if"
    storage-energy-in-wh-if:
      method: Multiply
      path: builtin
      global-config:
        input-parameters: ["storage-watts-if", "duration-in-hours"]
        output-parameter: "storage-wh-if"
    storage-energy-to-kwh-if:
      path: "builtin"
      method: Coefficient
      global-config:
        input-parameter: storage-wh-if
        coefficient: 0.001
        output-parameter: storage-kwh-if

    ## Github storage for if-data
    #############################

    storage-and-traffic-from-github-if-data:
      method: Github
      path: if-github-plugin
      global-config:
        repo: Green-Software-Foundation/if-data
    copy-param-if-data-repo-size:
      path: builtin
      method: Copy
      global-config:
        keep-existing: false
        from: size
        to: repo-size-if-data
    copy-param-if-data-clones:
      path: builtin
      method: Copy
      global-config:
        keep-existing: false
        from: clones
        to: repo-clones-if-data
    storage-in-mb-to-tb-if-data:
      method: Coefficient
      path: builtin
      global-config:
        input-parameter: repo-size-if-data # size comes from github api and represents repo size in gb
        coefficient: 0.000001 # convert size to tb
        output-parameter: storage-tb-if-data
    storage-energy-in-watts-if-data:
      method: Multiply
      path: builtin
      global-config:
        input-parameters: ["storage-tb-if-data", "watts-per-tb"]
        output-parameter: "storage-watts-if-data"
    storage-energy-in-wh-if-data:
      method: Multiply
      path: builtin
      global-config:
        input-parameters: ["storage-watts-if-data", "duration-in-hours"]
        output-parameter: "storage-wh-if-data"
    storage-energy-to-kwh-if-data:
      path: "builtin"
      method: Coefficient
      global-config:
        input-parameter: storage-wh-if-data
        coefficient: 0.001
        output-parameter: storage-kwh-if-data

    ## Github storage for if-docs
    #############################

    storage-and-traffic-from-github-if-docs:
      method: Github
      path: if-github-plugin
      global-config:
        repo: Green-Software-Foundation/if-docs
    copy-param-if-docs-repo-size:
      path: builtin
      method: Copy
      global-config:
        keep-existing: false
        from: size
        to: repo-size-if-docs
    copy-param-if-docs-clones:
      path: builtin
      method: Copy
      global-config:
        keep-existing: false
        from: clones
        to: repo-clones-if-docs
    storage-in-mb-to-tb-if-docs:
      method: Coefficient
      path: builtin
      global-config:
        input-parameter: repo-size-if-docs # size comes from github api and represents repo size in gb
        coefficient: 0.000001 # convert size to tb
        output-parameter: storage-tb-if-docs
    storage-energy-in-watts-if-docs:
      method: Multiply
      path: builtin
      global-config:
        input-parameters: ["storage-tb-if-docs", "watts-per-tb"]
        output-parameter: storage-watts-if-docs
    storage-energy-in-wh-if-docs:
      method: Multiply
      path: builtin
      global-config:
        input-parameters: ["storage-watts-if-docs", "duration-in-hours"]
        output-parameter: storage-wh-if-docs
    storage-energy-to-kwh-if-docs:
      path: builtin
      method: Coefficient
      global-config:
        input-parameter: storage-wh-if-docs
        coefficient: 0.001
        output-parameter: storage-kwh-if-docs
    sum-storage-energy-components:
      method: Sum
      path: builtin
      global-config:
        input-parameters: ['storage-kwh-if','storage-kwh-if-data','storage-kwh-if-docs']
        output-parameter: 'storage-energy-kwh'
    
    # data downloaded from if repositories
    ######################################

    total-data-downloaded-from-if-repo:
      method: Multiply
      path: 'builtin'
      global-config:
        input-parameters: ["repo-size-if", "repo-clones-if"]
        output-parameter: "data-egress-if" # data transferred in GB
    total-data-downloaded-from-if-docs-repo:
      method: Multiply
      path: 'builtin'
      global-config:
        input-parameters: ["repo-size-if-docs", "repo-clones-if-docs"]
        output-parameter: "data-egress-if-docs" # data transferred in GB
    total-data-downloaded-from-if-data-repo:
      method: Multiply
      path: 'builtin'
      global-config:
        input-parameters: ["repo-size-if-data", "repo-clones-if-data"]
        output-parameter: "data-egress-if-data" # data transferred in GB
    sum-repo-download-components:
      method: Sum
      path: builtin
      global-config:
        input-parameters: ['data-egress-if','data-egress-if-docs','data-egress-if-data']
        output-parameter: total-data-egress
    repo-downloads-to-energy:
      method: Coefficient
      path: 'builtin'
      global-config:
        input-parameter: total-data-egress
        coefficient: 0.001 # from https://www.cloudcarbonfootprint.org/docs/methodology/#networking
        output-parameter: github-downloads-energy-kwh

    # Github CI/CD
    ##############

    eco-ci-github-actions-if:
      method: EcoCI
      path: "if-eco-ci-plugin"
      global-config:
        repo: "Green-Software-Foundation/if"
        branch: all
        workflow: 66389738
        start-date: 2024-07-14T08:30
        end-date: 2024-08-14T10:30
    copy-param-energy-ci-cd-if:
      path: builtin
      method: Copy
      global-config:
        keep-existing: false
        from: energy
        to: ci-cd-energy-kwh


    # NOTE
    # temporarily calculating CI/CD energy offline from this page https://metrics.green-coding.io/ci.html?repo=Green-Software-Foundation/if&branch=main&workflow=66389738#
    # when the eco-ci plugin is updated to return totals for a time range, then we can reinstate the above pipeline


    ## NPM Storage
    ##############

    storage-in-gb-to-tb-npm:
      method: Coefficient
      path: builtin
      global-config:
        input-parameter: npm-storage-size
        coefficient: 0.001 # convert size to tb
        output-parameter: storage-tb-npm
    storage-energy-in-watts-npm:
      method: Multiply
      path: builtin
      global-config:
        input-parameters: ["storage-tb-npm", "watts-per-tb"]
        output-parameter: storage-watts-npm
    storage-energy-in-wh-npm:
      method: Multiply
      path: builtin
      global-config:
        input-parameters: ["storage-watts-npm", "duration-in-hours"]
        output-parameter: storage-wh-npm
    storage-energy-to-kwh-npm:
      path: builtin
      method: Coefficient
      global-config:
        input-parameter: storage-wh-npm
        coefficient: 0.001
        output-parameter: storage-energy-kwh-npm    

    ## NPM download energy
    ######################

    total-data-downloaded-from-npm:
      method: Multiply
      path: 'builtin'
      global-config:
        input-parameters: ["npm-storage-size", "npm-downloads-per-month"]
        output-parameter: data-egress-npm
    npm-downloads-to-energy:
      method: Coefficient
      path: 'builtin'
      global-config:
        input-parameter: data-egress-npm
        coefficient: 0.001 # from https://www.cloudcarbonfootprint.org/docs/methodology/#networking
        output-parameter: npm-downloads-energy-kwh


    # Running IF
    ############

    interpolate-power-curve:
      path: builtin
      method: Interpolation
      global-config:
        method: linear
        x:
          - 0
          - 10
          - 50
          - 100
        'y':
          - 0.12
          - 0.32
          - 0.75
          - 1.02
        input-parameter: cpu/utilization
        output-parameter: cpu-factor
    cpu-factor-to-wattage:
      path: builtin
      method: Multiply
      global-config:
        input-parameters:
          - cpu-factor
          - thermal-design-power
        output-parameter: cpu-wattage
    cpu-wattage-times-run-time-duration:
      path: builtin
      method: Multiply
      global-config:
        input-parameters:
          - cpu-wattage
          - run-time-duration
        output-parameter: cpu-wattage-times-run-time-duration
    cpu-wattage-to-energy-kwh:
      path: builtin
      method: Divide
      global-config:
        numerator: cpu-wattage-times-run-time-duration
        denominator: 3600000 # converts watts to kwh
        output: cpu-energy-per-run
    cpu-per-run-to-cpu-per-month:
      path: builtin
      method: Multiply
      global-config:
        input-parameters: [cpu-energy-per-run, runs-per-month]
        output-parameter: if-run-cpu-energy
    
    ## Memory used per IF run
    #########################

    memory-coefficient-correction: # memory coefficient in CCF is given /GB/hr - we want to convert to /GB/run-time-duration then x by run duration in s
      path: builtin
      method: Coefficient
      global-config:
        input-parameter: run-time-duration
        coefficient: 0.000006533333 # this is 0.000392/60 = KW/GB/H -> KW/GB/s
        output-parameter: memory-coefficient
    memory-energy-per-run:
      path: builtin
      method: Multiply
      global-config:
        input-parameters: [if-run-memory-gb, memory-coefficient]
        output-parameter: if-run-memory-energy-per-run
    memory-energy-per-run-to-memory-energy-per-month:
      path: builtin
      method: Multiply
      global-config:
        input-parameters: [if-run-memory-energy-per-run, runs-per-month]
        output-parameter: if-run-memory-energy

    ## Sum energy components and convert to carbon
    ##############################################

    sum-energy-components:
      method: Sum
      path: builtin
      global-config:
        input-parameters: ['storage-energy-kwh','github-downloads-energy-kwh','ci-cd-energy-kwh','storage-energy-kwh-npm', 'npm-downloads-energy-kwh', 'if-run-cpu-energy','if-run-memory-energy']
        output-parameter: 'energy'

    energy-to-carbon:
      method: Multiply
      path: "builtin"
      global-config:
        input-parameters: ["energy", "grid-intensity"]
        output-parameter: "operational-carbon"

    ## Sum embodied and operational carbon
    ######################################
    sum-carbon-components:
      method: Sum
      path: builtin
      global-config:
        input-parameters: ['operational-carbon', 'embodied-carbon-for-gh-server', 'embodied-carbon-of-user-devices']
        output-parameter: 'carbon'


    ## Calculate SCI
    ################

    sci:
      kind: plugin
      method: Sci
      path: "builtin"
      global-config:
        functional-unit: runs-per-month

tree:
  children:
    if:
      pipeline:
        compute:
          - duration-in-hours
          - storage-and-traffic-from-github-if
          - copy-param-if-repo-size
          - copy-param-if-clones
          - storage-in-mb-to-tb-if
          - storage-energy-in-watts-if
          - storage-energy-in-wh-if
          - storage-energy-to-kwh-if
          - storage-and-traffic-from-github-if-data
          - copy-param-if-data-repo-size
          - copy-param-if-data-clones
          - storage-in-mb-to-tb-if-data
          - storage-energy-in-watts-if-data
          - storage-energy-in-wh-if-data
          - storage-energy-to-kwh-if-data
          - storage-and-traffic-from-github-if-docs
          - copy-param-if-docs-repo-size
          - copy-param-if-docs-clones
          - storage-in-mb-to-tb-if-docs
          - storage-energy-in-watts-if-docs
          - storage-energy-in-wh-if-docs
          - storage-energy-to-kwh-if-docs
          - sum-storage-energy-components
          - total-data-downloaded-from-if-repo
          - total-data-downloaded-from-if-docs-repo
          - total-data-downloaded-from-if-data-repo
          - sum-repo-download-components
          # Temporarily disabling these plugins in favour of hardcoding value in defaults
          - eco-ci-github-actions-if
          - copy-param-energy-ci-cd-if
          - repo-downloads-to-energy
          - storage-in-gb-to-tb-npm
          - storage-energy-in-watts-npm
          - storage-energy-in-wh-npm
          - storage-energy-to-kwh-npm
          - total-data-downloaded-from-npm
          - npm-downloads-to-energy
          - interpolate-power-curve
          - cpu-factor-to-wattage
          - cpu-wattage-times-run-time-duration
          - cpu-wattage-to-energy-kwh
          - cpu-per-run-to-cpu-per-month
          - memory-coefficient-correction
          - memory-energy-per-run
          - memory-energy-per-run-to-memory-energy-per-month
          - sum-energy-components
          - energy-to-carbon
          - sum-carbon-components
          - sci # gCO2eq per run

      defaults:
        watts-per-tb: 0.65 # https://www.cloudcarbonfootprint.org/docs/methodology/#storage
        grid-intensity: 494 # world average according to https://sustainablewebdesign.org/estimating-digital-emissions/
        npm-storage-size: 0.00000135 # in GB, retrieved from npm site
        npm-downloads-per-month: 1080
        runs-per-month: 3000 # assuming 20 per user, 150 users = 3000
        cpu/utilization: 95
        thermal-design-power: 45
        run-time-duration: 7 #how long to run IF on given hardware
        if-run-memory-gb: 0.48
        embodied-carbon-for-gh-server: 0.117  # embodied carbon for our fraction of the server hosting our GH repos
        embodied-carbon-of-user-devices: 26.94 # total embodied carbon for all user devices
        embodied-carbon-npm-server: 0.00084 # embodied carbon for our fraction of the server hosting our npm package
      inputs:
        - timestamp: '2024-08-13T00:00'
          duration: 2419200
